site_name: funfunzmc
nav:
    - Home: index.md
    - Usage:
        - Quickstart: usage/quickstart.md
        - Plugin: usage/plugin.md
        - Standalone: usage/standalone.md
    - Configuration:
        - Config: configuration/config.md
        - Settings: configuration/settings.md
    - End Goals: endgoals.md
    - Contributing: contributing.md
theme: material
repo_name: 'JWebCoder/funfunzmc'
repo_url: 'https://github.com/JWebCoder/funfunzmc'
edit_uri: edit/master/srcDocs/
markdown_extensions:
    - codehilite