name: Deploy

on:
  push:
    branches:
      - master 

env:
  DB_HOST: ryfqldzbliwmq6g5.chr7pe7iynqr.eu-west-1.rds.amazonaws.com
  DB_USER: vz4nt766z0tffpi8
  DB_PASS: ${{secrets.DB_PASS}}
  DB_NAME: zucf1on9sjbl139n

jobs:
  nodejs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.6.8
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: funfunz
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          delay: 10
        env:
          HD_NPM_CONFIG_PRODUCTION: false
          HD_NODE_MODULES_CACHE: false

  mysql:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: mysql -h $DB_HOST -u $DB_USER -p$DB_PASS $DB_NAME < src/test/test.sql